#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS := $(XASCODE_PATH)/ESP32

PROJECT_NAME := NYE-Countdown

include $(IDF_PATH)/make/project.mk

